- name: Install packages
  package:
    name: nginx
    state: latest
  
- name: nginx configuration file
  copy:
    dest: /etc/nginx/nginx.conf
    src: etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  
  
- name: To shift site contents
  copy:
    dest: /var/www/html/index.html
    src: /home/subbu/plays/nginx/files/html_demo_site-main/index.html
    owner: root
    group: root
    mode: 0755
  notify: reload nginx
